# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.0.0
group=com.rethinkqaq.totemdoll
java_version=21

# Common
mod_name=Totem Doll
mod_author=RethinkQAQ
mod_id=totemdoll
license=CC0-1.0
credits=
description=A client-side mod that turns the Totem of Undying into a configurable Minecraft-style doll.
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
