license {
    header = rootProject.file('HEADER.txt')
    include '**/*.java'
    skipExistingHeaders = true
    ignoreFailures = false

    headerDefinitions {
        SLASHSTAR_STYLE_NEWLINE {
            firstLine = '/*'
            beforeEachLine = ' * '
            endLine = ' */' + System.lineSeparator()
            afterEachLine = ''
            skipLinePattern = null
            firstLineDetectionPattern = '(\\s|\\t)*/\\*.*$'
            lastLineDetectionPattern = '.*\\*/(\\s|\\t)*$'
            allowBlankLines = false
            isMultiline = true
            padLines = false
        }
    }
    mapping {
        java = 'SLASHSTAR_STYLE_NEWLINE'
    }
    ext {
        name = project.findProperty('mod_name') ?: 'Totem Doll'
        author = 'Rethink_QAQ'
        year = Calendar.getInstance().get(Calendar.YEAR).toString()
    }
}
