pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Fabric'
                    url = uri('https://maven.fabricmc.net')
                }
            }
            filter {
                includeGroup('net.fabricmc')
                includeGroup('fabric-loom')
            }
        }
        maven {
            name = 'KikuGie'
            url = uri('https://maven.kikugie.dev/releases')
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Sponge'
                    url = uri('https://repo.spongepowered.org/repository/maven-public')
                }
            }
            filter {
                includeGroupAndSubgroups("org.spongepowered")
            }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
    id 'dev.kikugie.stonecutter' version '0.7.11'
}

rootProject.name = 'TotemDoll'
include('common', 'fabric', 'neoforge')

stonecutter {
    kotlinController = false
    centralScript = 'build.gradle'
    create(rootProject) {
        versions '1.21.1-fabric', '1.21.1-neoforge', '1.21.4-fabric', '1.21.4-neoforge'
        vcsVersion = '1.21.1-fabric'
    }
}

// This should match the folder name of the project, or else IDEA may complain (see https://youtrack.jetbrains.com/issue/IDEA-317606)
