# Java
enable_platforms=fabric,neoforge
java.version=21

# Minecraft
minecraft_version=1.21.3
publish_version=1.21.2,1.21.3
minecraft_version_range_fabric=>=1.21.2 <=1.21.3
minecraft_version_range_neoforge=[1.21.2,1.21.3]

# Mappings
deps.parchment=2024.12.07

# Fabric
deps.fabric-loader=0.19.5
deps.fabric-loader-min=0.11.0
deps.fabric-api=0.114.1
deps.modmenu=12.0.1

# NeoForge
deps.neoforge=21.3.97
deps.neoforge-min=21.3
