# Java
enable_platforms=fabric,neoforge
java.version=25

# Minecraft
minecraft_version=26.2
min_minecraft_version=26.2
minecraft_version_range_fabric=>=26.2
minecraft_version_range_neoforge=[26.2,26.3)

# Mappings
deps.parchment=

# Fabric
deps.fabric-loader=0.19.3
deps.fabric-loader-min=0.11.0
deps.fabric-api=0.156.0
deps.modmenu=20.0.1

# NeoForge
deps.neoforge=26.2.0.53-beta
deps.neoforge-min=26.2
