modLoader="javafml"
loaderVersion="[4,)"
license="${modLicense}"
issueTrackerURL="https://github.com/${modGitHub}/issues"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
iconFile="itemdoll.png"
authors="${modAuthor}"
description='''${modDescription}'''

[[mixins]]
config="${modId}.mixins.json"
[[mixins]]
config="${modId}.neoforge.mixins.json"

[[dependencies.${modId}]]
modId="neoforge"
type="required"
versionRange="[${neoForgeMinVersion},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${modId}]]
modId="minecraft"
type="required"
versionRange="${minecraftVersionRangeNeoForge}"
ordering="NONE"
side="CLIENT"
