modLoader="javafml"
loaderVersion="[4,)"
license="${modLicense}"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
logoFile="itemdoll.png"
authors="${modAuthor}"
description='''${modDescription}'''

[[mixins]]
config="${modId}.mixins.json"
[[mixins]]
config="${modId}.neoforge.mixins.json"

[[dependencies.${modId}]]
modId="neoforge"
type="required"
versionRange="[${neoForgeVersion},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${modId}]]
modId="minecraft"
type="required"
versionRange="[${minMinecraftVersion},${minecraftVersion}]"
ordering="NONE"
side="CLIENT"
